version: '3.7'

networks:
  backend-app:
    driver: bridge

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_PASSWORD=123mudar
      - RABBITMQ_USERNAME=admin
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - backend-app
    volumes:
      - 'rabbitmqstats_data:/bitnami'      

  appcadastro:
    image: 'wsoliveiraudia/appcadastro_labs:latest'
    networks:
      - backend-app
    depends_on: 
      - 'rabbitmq'
    ports: 
      - '8010:8010'
    environment: 
      - HOST_RABBITMQ=rabbitmq

  apprecurso:
    image: 'wsoliveiraudia/apprecurso_labs:latest'
    networks:
      - backend-app
    depends_on: 
      - 'rabbitmq'
    ports: 
      - '8020:8020'
    environment: 
      - HOST_RABBITMQ=rabbitmq      

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123mudar
    ports:
      - "27017:27017"      
    networks:
      - backend-app      
    volumes:
      - ./MongoDB:/data/db      

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123mudar
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123mudar
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - backend-app
    depends_on: 
      - mongo

volumes:
  rabbitmqstats_data:
    driver: local      