"""empty message

Revision ID: 2b51e44f8316
Revises: 
Create Date: 2021-09-07 20:15:10.937254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b51e44f8316'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_recurso', sa.String(length=255), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurso')
    # ### end Alembic commands ###
