apiVersion: apps/v1
kind: Deployment
metadata:
  name: appcadastro-deployment
  namespace: microserviceslabs
spec:
  selector:
    matchLabels:
      app: appcadastro
  replicas: 1
  template:
    metadata:
      labels:
        app: appcadastro
    spec:
      containers:
      - name: appcadastro
        image: wsoliveiraudia/appcadastro_labs:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"        
        ports:
        - containerPort: 8010