apiVersion: v1
kind: Service
metadata:
  name: appcadastro-service
  namespace: microserviceslabs
  labels:
    app: appcadastro
spec:
  selector:
    app: appcadastro
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010